[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43

build_flags =
    ; Кажемо TFT_eSPI: конфіг уже заданий тут, User_Setup.h не читай.
    -D USER_SETUP_LOADED=1

    ; --- Драйвер дисплея ---
    -D ILI9341_2_DRIVER=1

    ; --- Розміри матриці (портретна орієнтація, "рідна" для драйвера) ---
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320

    ; --- Розводка CYD: до яких ніжок ESP32 припаяний дисплей ---
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1

    ; --- Підсвітка ---
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH

    ; --- Шрифти ---
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1

    ; --- Швидкість шини SPI ---
    -D SPI_FREQUENCY=40000000
